# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :character_skill, :class => 'CharacterSkills' do
    alchemy false
    blacksmith 1
    create_potion 1
    create_scroll 1
    create_trap 1
    herbal_lore false
    legerdemain false
    merchant false
    teacher 1
    wear_extra_armor 1
    break_command 1
    claws false
    gypsy_curse 1
    racial_assassinate false
    racial_dodge false
    racial_proficiency false
    racial_slay false
    resist_binding 1
    resist_command 1
    resist_element 1
    resist_fear 1
    resist_magic false
    resist_necromancy 1
    resist_poison 1
    archery false
    florentine false
    one_handed_blunt false
    one_handed_edged false
    one_handed_master false
    polearm false
    small_weapon false
    staff false
    style_master false
    thrown_weapon false
    two_handed_blunt false
    two_handed_sword false
    two_handed_master false
    two_weapons false
    weapon_master false
    assassinate 1
    back_attack 1
    backstab 1
    critical_attack 1
    disarm 1
    dodge 1
    evade 1
    eviscerate 1
    parry 1
    riposte 1
    shatter 1
    shield false
    slay 1
    stun_limb 1
    terminate 1
    waylay false
    weapon_proficiency 1
    read_and_write false
    read_magic false
    first_aid false
    healing_arts false
    celestial_level_1 1
    celestial_level_2 1
    celestial_level_3 1
    celestial_level_4 1
    celestial_level_5 1
    celestial_level_5 1
    celestial_level_6 1
    celestial_level_7 1
    celestial_level_8 1
    celestial_level_9 1
    formal_celestial 1
    earth_level_1 1
    earth_level_2 1
    earth_level_3 1
    earth_level_4 1
    earth_level_5 1
    earth_level_6 1
    earth_level_7 1
    earth_level_8 1
    earth_level_9 1
    formal_earth 1
  end
end
