# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Race.create(name: 'Barbarian')
Race.create(name: 'Biata')
Race.create(name: 'Dark Elf')
Race.create(name: 'Dryad')
Race.create(name: 'Dwarf')
Race.create(name: 'Elf')
Race.create(name: 'Gypsy')
Race.create(name: 'High Ogre')
Race.create(name: 'High Orc')
Race.create(name: 'Hobling')
Race.create(name: 'Human')
Race.create(name: 'Mystic Wood Elf')
Race.create(name: 'Sarr')
Race.create(name: 'Stone Elf')
Race.create(name: 'Wylderkin')

Skill.create(name: 'Alchemy', fighter_cost: 6, scout_cost: 5, rogue_cost: 3, adept_cost: 4, scholar_cost: 4, templar_cost: 6, artisan_cost: 3)
Skill.create(name: 'Blacksmith', fighter_cost: 3, scout_cost: 3, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 3, artisan_cost: 3)
Skill.create(name: 'Create Potion', fighter_cost: 6, scout_cost: 6, rogue_cost: 6, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 3)
Skill.create(name: 'Create Scroll', fighter_cost: 6, scout_cost: 6, rogue_cost: 6, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 3)
Skill.create(name: 'Create Trap', fighter_cost: 6, scout_cost: 4, rogue_cost: 3, adept_cost: 4, scholar_cost: 6, templar_cost: 6, artisan_cost: 3)
Skill.create(name: 'Herbal Lore', fighter_cost: 6, scout_cost: 5, rogue_cost: 3, adept_cost: 4, scholar_cost: 4, templar_cost: 6, artisan_cost: 3)
Skill.create(name: 'Legerdemain', fighter_cost: 10, scout_cost: 8, rogue_cost: 4, adept_cost: 8, scholar_cost: 10, templar_cost: 10, artisan_cost: 8)
Skill.create(name: 'Merchant', fighter_cost: 3, scout_cost: 2, rogue_cost: 1, adept_cost: 2, scholar_cost: 3, templar_cost: 3, artisan_cost: 1)
Skill.create(name: 'Teacher', fighter_cost: 1, scout_cost: 1, rogue_cost: 1, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 1)
Skill.create(name: 'Wear Extra Armor', fighter_cost: 1, scout_cost: 1, rogue_cost: 1, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 1)
Skill.create(name: 'Break Command', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Claws', fighter_cost: 8, scout_cost: 8, rogue_cost: 8, adept_cost: 8, scholar_cost: 8, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Gypsy Curse', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Racial Assassinate', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Racial Dodge', fighter_cost: 10, scout_cost: 10, rogue_cost: 10, adept_cost: 10, scholar_cost: 10, templar_cost: 10, artisan_cost: 10)
Skill.create(name: 'Racial Proficiency', fighter_cost: 10, scout_cost: 10, rogue_cost: 10, adept_cost: 10, scholar_cost: 10, templar_cost: 10, artisan_cost: 10)
Skill.create(name: 'Racial Slay', fighter_cost: 6, scout_cost: 6, rogue_cost: 6, adept_cost: 6, scholar_cost: 6, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Resist Binding', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Resist Command', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Resist Element', fighter_cost: 3, scout_cost: 3, rogue_cost: 3, adept_cost: 3, scholar_cost: 3, templar_cost: 3, artisan_cost: 3)
Skill.create(name: 'Resist Fear', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Resist Magic', fighter_cost: 5, scout_cost: 5, rogue_cost: 5, adept_cost: 5, scholar_cost: 5, templar_cost: 5, artisan_cost: 5)
Skill.create(name: 'Resist Necromancy', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Resist Poison', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Archery', fighter_cost: 6, scout_cost: 6, rogue_cost: 6, adept_cost: 8, scholar_cost: 12, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Florentine', fighter_cost: 4, scout_cost: 6, rogue_cost: 6, adept_cost: 6, scholar_cost: 8, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'One Handed Blunt', fighter_cost: 3, scout_cost: 4, rogue_cost: 4, adept_cost: 5, scholar_cost: 6, templar_cost: 5, artisan_cost: 5)
Skill.create(name: 'One Handed Edged', fighter_cost: 5, scout_cost: 5, rogue_cost: 5, adept_cost: 7, scholar_cost: 10, templar_cost: 7, artisan_cost: 7)
Skill.create(name: 'One Handed Master', fighter_cost: 7, scout_cost: 8, rogue_cost: 8, adept_cost: 10, scholar_cost: 14, templar_cost: 10, artisan_cost: 10)
Skill.create(name: 'Polearm', fighter_cost: 8, scout_cost: 12, rogue_cost: 12, adept_cost: 12, scholar_cost: 16, templar_cost: 12, artisan_cost: 12)
Skill.create(name: 'Small Weapon', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Staff', fighter_cost: 4, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Style Master', fighter_cost: 10, scout_cost: 15, rogue_cost: 15, adept_cost: 15, scholar_cost: 20, templar_cost: 15, artisan_cost: 15)
Skill.create(name: 'Thrown Weapon', fighter_cost: 2, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Two Handed Blunt', fighter_cost: 6, scout_cost: 8, rogue_cost: 8, adept_cost: 8, scholar_cost: 12, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Two Handed Sword', fighter_cost: 8, scout_cost: 12, rogue_cost: 12, adept_cost: 12, scholar_cost: 16, templar_cost: 12, artisan_cost: 12)
Skill.create(name: 'Two Handed Master', fighter_cost: 10, scout_cost: 16, rogue_cost: 16, adept_cost: 16, scholar_cost: 20, templar_cost: 16, artisan_cost: 16)
Skill.create(name: 'Two Weapons', fighter_cost: 2, scout_cost: 4, rogue_cost: 4, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Weapon Master', fighter_cost: 15, scout_cost: 20, rogue_cost: 20, adept_cost: 20, scholar_cost: 25, templar_cost: 20, artisan_cost: 20)
Skill.create(name: 'Assassinate', fighter_cost: 8, scout_cost: 3, rogue_cost: 3, adept_cost: 4, scholar_cost: 8, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Back Attack', fighter_cost: 6, scout_cost: 3, rogue_cost: 3, adept_cost: 3, scholar_cost: 8, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Backstab', fighter_cost: 6, scout_cost: 6, rogue_cost: 3, adept_cost: 6, scholar_cost: 8, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Critical Attack', fighter_cost: 3, scout_cost: 3, rogue_cost: 5, adept_cost: 6, scholar_cost: 8, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Disarm', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 3, scholar_cost: 8, templar_cost: 3, artisan_cost: 8)
Skill.create(name: 'Evade', fighter_cost: 8, scout_cost: 3, rogue_cost: 3, adept_cost: 4, scholar_cost: 8, templar_cost: 8, artisan_cost: 8)
Skill.create(name: 'Eviscerate', fighter_cost: 5, scout_cost: 7, rogue_cost: 14, adept_cost: 14, scholar_cost: 14, templar_cost: 7, artisan_cost: 14)
Skill.create(name: 'Parry', fighter_cost: 4, scout_cost: 4, rogue_cost: 8, adept_cost: 8, scholar_cost: 8, templar_cost: 5, artisan_cost: 8)
Skill.create(name: 'Riposte', fighter_cost: 5, scout_cost: 5, rogue_cost: 5, adept_cost: 6, scholar_cost: 8, templar_cost: 6, artisan_cost: 8)
Skill.create(name: 'Shatter', fighter_cost: 3, scout_cost: 3, rogue_cost: 3, adept_cost: 4, scholar_cost: 8, templar_cost: 4, artisan_cost: 8)
Skill.create(name: 'Shield', fighter_cost: 6, scout_cost: 10, rogue_cost: 10, adept_cost: 10, scholar_cost: 12, templar_cost: 10, artisan_cost: 10)
Skill.create(name: 'Slay', fighter_cost: 4, scout_cost: 4, rogue_cost: 8, adept_cost: 8, scholar_cost: 8, templar_cost: 5, artisan_cost: 8)
Skill.create(name: 'Stun Limb', fighter_cost: 3, scout_cost: 3, rogue_cost: 3, adept_cost: 4, scholar_cost: 8, templar_cost: 4, artisan_cost: 8)
Skill.create(name: 'Terminate', fighter_cost: 12, scout_cost: 6, rogue_cost: 4, adept_cost: 6, scholar_cost: 12, templar_cost: 12, artisan_cost: 12)
Skill.create(name: 'Waylay', fighter_cost: 12, scout_cost: 8, rogue_cost: 6, adept_cost: 8, scholar_cost: 12, templar_cost: 12, artisan_cost: 12)
Skill.create(name: 'Weapon Proficiency', fighter_cost: 3, scout_cost: 6, rogue_cost: 6, adept_cost: 6, scholar_cost: 8, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Read And Write', fighter_cost: 6, scout_cost: 6, rogue_cost: 6, adept_cost: 3, scholar_cost: 3, templar_cost: 3, artisan_cost: 3)
Skill.create(name: 'Read Magic', fighter_cost: 8, scout_cost: 8, rogue_cost: 6, adept_cost: 4, scholar_cost: 4, templar_cost: 4, artisan_cost: 6)
Skill.create(name: 'First Aid', fighter_cost: 2, scout_cost: 2, rogue_cost: 2, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Healing Arts', fighter_cost: 6, scout_cost: 6, rogue_cost: 4, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 4)
Skill.create(name: 'Celestial Level 1', fighter_cost: 3, scout_cost: 3, rogue_cost: 2, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 1)
Skill.create(name: 'Celestial Level 2', fighter_cost: 3, scout_cost: 3, rogue_cost: 2, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 2)
Skill.create(name: 'Celestial Level 3', fighter_cost: 6, scout_cost: 6, rogue_cost: 4, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Celestial Level 4', fighter_cost: 6, scout_cost: 6, rogue_cost: 4, adept_cost: 3, scholar_cost: 2, templar_cost: 3, artisan_cost: 3)
Skill.create(name: 'Celestial Level 5', fighter_cost: 9, scout_cost: 9, rogue_cost: 6, adept_cost: 3, scholar_cost: 3, templar_cost: 3, artisan_cost: 4)
Skill.create(name: 'Celestial Level 6', fighter_cost: 9, scout_cost: 9, rogue_cost: 6, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Celestial Level 7', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 5, scholar_cost: 4, templar_cost: 5, artisan_cost: 5)
Skill.create(name: 'Celestial Level 8', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 5, scholar_cost: 4, templar_cost: 5, artisan_cost: 6)
Skill.create(name: 'Celestial Level 9', fighter_cost: 15, scout_cost: 15, rogue_cost: 10, adept_cost: 6, scholar_cost: 5, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Formal Celestial', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Earth Level 1', fighter_cost: 3, scout_cost: 3, rogue_cost: 2, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 1)
Skill.create(name: 'Earth Level 2', fighter_cost: 3, scout_cost: 3, rogue_cost: 2, adept_cost: 1, scholar_cost: 1, templar_cost: 1, artisan_cost: 2)
Skill.create(name: 'Earth Level 3', fighter_cost: 6, scout_cost: 6, rogue_cost: 4, adept_cost: 2, scholar_cost: 2, templar_cost: 2, artisan_cost: 2)
Skill.create(name: 'Earth Level 4', fighter_cost: 6, scout_cost: 6, rogue_cost: 4, adept_cost: 3, scholar_cost: 2, templar_cost: 3, artisan_cost: 3)
Skill.create(name: 'Earth Level 5', fighter_cost: 9, scout_cost: 9, rogue_cost: 6, adept_cost: 3, scholar_cost: 3, templar_cost: 3, artisan_cost: 4)
Skill.create(name: 'Earth Level 6', fighter_cost: 9, scout_cost: 9, rogue_cost: 6, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 4)
Skill.create(name: 'Earth Level 7', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 5, scholar_cost: 4, templar_cost: 5, artisan_cost: 5)
Skill.create(name: 'Earth Level 8', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 5, scholar_cost: 4, templar_cost: 5, artisan_cost: 6)
Skill.create(name: 'Earth Level 9', fighter_cost: 15, scout_cost: 15, rogue_cost: 10, adept_cost: 6, scholar_cost: 5, templar_cost: 6, artisan_cost: 6)
Skill.create(name: 'Formal Earth', fighter_cost: 12, scout_cost: 12, rogue_cost: 8, adept_cost: 4, scholar_cost: 3, templar_cost: 4, artisan_cost: 4)